### ISSUE TITLE
Filter bar not working when added on dashboard

### ISSUE THREAD

**Issue by MariaStrotou** [fbaligand/kibana-enhanced-table#122] opened 2020-07-27 08:03 UTC
Hi, on kibana 7.6.2 I have notice an issue regarding enhanced table plugin (1.9.1) and especially with its filter bar. 
When I add this visualization on a dashboard, the filter bar does not work properly (in dark theme). 
Also, this issue is reproduced with the light theme.

Please look the below screenshot: 
![Καταγffραφή](https://user-images.githubusercontent.com/24607886/88517870-34080000-cff8-11ea-8182-876aecf0530e.PNG)

In dashboard, when I click at ciel search button, nothing changes. It remains as it is.
However when I am editing it from visualization tab, the filter bar is working perfect.

Thank you for your support.

**Comment by fbaligand** [comment] 2020-07-27 12:43
Thanks for the issue and details. 
Could you take a screenshot of the checked options for filter bar? So that I can reproduce your issue.

**Comment by MariaStrotou** [comment] 2020-07-27 12:56
Of course, please look the below screenshot:

![Καταγραφή](https://user-images.githubusercontent.com/24607886/88544211-b658ea00-d021-11ea-8815-09548790f134.PNG)

**Comment by fbaligand** [comment] 2020-07-27 13:15
Thank you, I will look at it.

**Comment by fbaligand** [comment] 2020-07-28 22:19
Hi,

I just realize that you checked "Filter as you type" option.
When you check this option, search button is disabled, because table filtering is done directly and synchronously when you type some text in filter bar.

**Comment by fbaligand** [comment] 2020-07-28 22:20
Hi,

I just realize that you checked "Filter as you type" option.
When you check this option, search button is disabled, because table filtering is done directly and synchronously when you type some text in filter bar.

**Comment by MariaStrotou** [comment] 2020-07-30 09:59
Hi @fbaligand and thank you very much for your prompt reply!
I follow your instruction above, and I tried again.
Please look below my screenshot of the checked options for filter bar:
![Καταγραφή](https://user-images.githubusercontent.com/24607886/88909787-37072880-d264-11ea-9c96-63bcabc2816b.PNG)

Even if I checked only the `Show filter bar`  and `Filter each term separately `, the problem remains in the dashboard tab.

**Comment by fbaligand** [comment] 2020-07-30 10:17
Well, I did some test with kibana 7.6, and didn’t reproduce your issue. 
So I’m quite annoyed, because at this point, I can’t help you.

**Comment by MariaStrotou** [comment] 2020-07-30 12:20
That's very strange.. :/ 
As I kindly mentioned, I am using kibana 7.6.2. Maybe enhanced table would be treated differently in Kibana 7.6 than in Kibana 7.6.2. 
Of course, it is a thought of mine.

**Comment by fbaligand** [comment] 2020-07-31 10:47
Well, I tested with Kibana 7.6.0.
But I would be very surprised that there is a difference with Kibana 7.6.2

**Comment by fbaligand** [comment] 2020-07-31 11:02
Hi @MariaStrotou, 

I just tried with Kibana 7.6.2, enhanced table 1.9.1, and last options you screenshot => it works fine.
I don't reproduce your issue.
If I click on "filter" button on type on [ENTER] keyboard touch, filtering is done as expected.

What browser and browser version do you use?

**Comment by MariaStrotou** [comment] 2020-08-20 11:58
Sorry for the delay reply @fbaligand 
Regarding the browser and browser version I use, please see the followings:
- Google Chrome Version: 84.0.4147.135 (Official Build) (64-bit)
- Firefox Version: 79.0 (64-bit)

In both browsers I face the same problem.

**Comment by fbaligand** [comment] 2020-08-20 22:56
Thanks for feedback.
I tested with these 2 browsers and don’t reproduce the issue. 
So I really don’t understand why you get this issue.

**Comment by fbaligand** [comment] 2020-10-04 23:38
This error is not reproducible on a fresh new install, and a tip has been given to avoid such an error.
So I close the issue.

**Closed by fbaligand** 2020-10-04 23:38 UTC
