### ISSUE TITLE
Query bar gone after installing enchanced table 1.11.0 in kibana 7.10.2

### ISSUE THREAD

**Issue by ddelliosRJ** [fbaligand/kibana-enhanced-table#177] opened 2021-02-08 11:55 UTC
Greetings again, 

I am facing this issue: I upgraded kibana from 7.9.2 to 7.10.2 and also upgraded plugin to latest version.

When installing, somehow search bar and time range vanishes and is restored after unistalling the plugin and restarting kibana again. 

Sorry to bother, let me know if you cannot reproduce.

Thanks,
Dimitris

**Comment by fbaligand** [comment] 2021-02-08 13:17
Hi,
Very weird issue...
You speak about Kibana core search bar? Or enhanced table filter bar ?

**Comment by ddelliosRJ** [comment] 2021-02-08 13:20
Core search bar.....very weird indeed. I also did an install in another kibana instance that was also running 7.10.1 with no issues.
I was suspicious that maybe previous enhanced table saved objects produced some kind of conflict but I also tested that on a clean setup and it was repeated.

**Comment by fbaligand** [comment] 2021-02-08 13:29
So you reproduce the issue on Kibana 7.10.1, but not on Kibana 7.10.2?

**Comment by ddelliosRJ** [comment] 2021-02-08 13:48
No, both my instances are 7.10.2, but only one of them has this issue, and it is the production one....:(

**Comment by ddelliosRJ** [comment] 2021-02-08 14:07
At this point I believe it's a system index that produces the conflict but I cannot experiment unfortunately

**Comment by fbaligand** [comment] 2021-02-08 16:10
Ok, it is very strange. 
But if you don’t see that issue on a kibana 7.10.2 instance, that is probably not because of enhanced table. 
by the way, I made some tests with kibana 7.10 and didn’t reproduce this issue.

**Comment by ddelliosRJ** [comment] 2021-02-08 16:12
Thanks for your time and effort. Hopefully it will resolve itself somehow!

**Comment by ddelliosRJ** [comment] 2021-02-09 09:59
Greetings again, please close the issue. It was fixed after clearing browser cache. It seems that it had cached previous kibana page from 7.7 without the navigation bar. No issues with enhanced table whatsoever. 

Thanks again for your time! Your work is awesome

**Comment by fbaligand** [comment] 2021-02-09 10:39
Thanks for the feedback. 
I have also some problems with browser cache since kibana 7.9. 
it is a known problem at Elastic.
Don’t hesitate to open an issue on kibana repository.

**Comment by fbaligand** [comment] 2021-02-09 10:39
As you ask it, I close the issue.

**Closed by fbaligand** 2021-02-09 10:39 UTC
Labels: question
