### ISSUE TITLE
Access time picker value

### ISSUE THREAD

**Issue by toog** [fbaligand/kibana-enhanced-table#137] opened 2020-09-08 14:33 UTC
Is it possible to add Function to retrieve the time picker date (min and max) ?

I need to calculate ratio value using the observality range of the time picker. 
Actualy i add a metric with a simple **min('@timestamp')** and another with the **max('@timestamp')** but if i have less documents than the time picker range i can't get the exact same range for my calculation.

thanks

**Comment by fbaligand** [comment] 2020-09-08 19:38
Hi @toog,

I close this issue, as it is a duplicate of #109

**Closed by fbaligand** 2020-09-08 19:38 UTC

**Comment by fbaligand** [comment] 2020-09-09 07:00
Don't hesitate to add a 👍 on the issue, it helps me to know which issues are most requested, and so, implement these ones.
