### ISSUE TITLE
Unable to see 'Options' tab in 7.6.2 Kibana

### ISSUE THREAD

**Issue by ravisarun** [fbaligand/kibana-enhanced-table#119] opened 2020-07-20 11:39 UTC
Hi, we have been using enhanced table from 6.4 version.  Recently, we had to migrate to 7.6.2.  After we migrated, we are unable to see 'options' tab in Enhanced table.  It shows up as empty.  Attaching a screenshot.  Please assist.

<img width="292" alt="Capture" src="https://user-images.githubusercontent.com/23431101/87933870-a5e9c200-caab-11ea-965f-6b0a3f677557.PNG">

**Comment by fbaligand** [comment] 2020-07-20 12:10
Do you have some error logs in your browser console?

**Comment by ravisarun** [comment] 2020-07-20 12:47
Thanks for the quick response.  Here is the error message from browser console. 

Error: [$compile:multidir] Multiple directives [draggableContainer (module: kibana), draggableContainer (module: kibana)] asking for 'draggableContainer' controller on: <div draggable-container="editorState.params.computedColumns" class="computed-columns">
https://errors.angularjs.org/1.7.9/$compile/multidir?p0=drag…arams.computedColumns%22%20class%3D%22computed-columns%22%3E
    r http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ke http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ve http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ie http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    link http://149.81.78.41:5601/bundles/commons.bundle.js:3
    pe http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    Re http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    Ie http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ae http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ae http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    se http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ie http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    ge http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    o http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    v http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    compile http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    watchCollection http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    $digest http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    evalAsync http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    completeTask http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    o http://149.81.78.41:5601/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
 <vis-editor-vis-options class="visEditorSidebar__options ng-pristine ng-untouched ng-valid" current-tab="sidebar.section" ng-model="_internalNgModelState" editor-state="state" has-histogram-agg="hasHistogramAgg" vis="vis" vis-data="visData" ui-state="uiState" visualize-editor="visualizeEditor" editor="tab.editor" on-agg-params-change="onAggParamsChange">

**Comment by ravisarun** [comment] 2020-07-20 13:43
I think it is because we customized enhanced-table plugin to create another plugin called util-enhanced-table.  After migrating to 7.6.2, I think something is conflicting and breaking both the plugins' 'Option' page.  After I deleted the util-enhanced-table plugin, iI can see the 'Options' tab in enhanced-table.  Will troubleshoot more.

**Comment by fbaligand** [comment] 2020-07-20 14:12
Thanks for your investigation. 
Indeed, the error lets me think about a conflict between 2 plugins declaring the same “draggable” component. 

Therefore, I’m curious: what brings more your “util-enhanced-table” ?

And if your “util-enhanced-table” adds some feature, don’t hesitate to make a pull request here :)

**Comment by ravisarun** [comment] 2020-07-21 04:24
Hi,  We had a requirement to select a bucket of data based on intersection of time range field rather than a fixed timestamp field.  So, we do some override of timefilter selection in the plugin.  We did it in a very crude way.  Need to spend some time in hardening it.

**Comment by fbaligand** [comment] 2020-07-21 04:46
Thank you for the details.
We could imagine a checkbox in options for that need. 
I guess that your time range intersection is defined in query, so is global for all buckets/metrics?

Concerning your issue, since kibana 7.7, dragula (that defines draggableContainer) is not anymore a dependency. So maybe it could fix your issue.

**Comment by fbaligand** [comment] 2020-10-04 23:41
The issue is not caused by enhanced table, but because a fork of enhanced table is installed aside enhanced table.
And I gave a tip to potentially avoid the issue.
So I close the issue.

**Closed by fbaligand** 2020-10-04 23:41 UTC
Labels: question
