### ISSUE TITLE
Error in Enhanced Table Request to Elasticsearch failed: {"error":{}}

### ISSUE THREAD

**Issue by umarfbajri** [fbaligand/kibana-enhanced-table#146] opened 2020-10-08 08:12 UTC
Hello All,,

I get error Like this went i use Enhanced Table in Kibana 7.5.0

Error in visualization
[enhanced_table_visualization] > Request to Elasticsearch failed: {"error":{}}

Visualization i get is Blank Table...

Why its Happen? and how to solve it? thanks before...

**Comment by fbaligand** [comment] 2020-10-08 21:18
Hi,

I just tested enhanced-table plugin v1.10.0 on Kibana 7.5, and it works great.
Could you tell me what enhanced-table plugin version do you use, and what is your configuration (buckets, metrics, computed columns, options). A screenshot is probably the easy way.

**Comment by fbaligand** [comment] 2020-10-11 17:54
Hi,

As it solves several other similar issues, can you try to do these actions:
- stop kibana
- remove $KIBANA_HOME/optimize folder
- start kibana
- empty your browser cache
- reload kibana url in browser

**Comment by umarfbajri** [comment] 2020-10-13 17:39
![image](https://user-images.githubusercontent.com/67785978/95895930-a39ab980-0db5-11eb-8f2b-8431c61c4f8b.png)

this the error i get, this save to do this actions?

> Hi,
> 
> As it solves several other similar issues, can you try to do these actions:
> 
> * stop kibana
> * remove $KIBANA_HOME/optimize folder
> * start kibana
> * empty your browser cache
> * reload kibana url in browser

**Comment by fbaligand** [comment] 2020-10-13 20:14
Well, given your screenshot, yes, you can avoid these actions.

Could you share the "Request" tab content?
Could you try same buckets/metrics with core "Data Table" visualization, to see if you reproduce the same issue?

**Comment by fbaligand** [comment] 2023-11-11 10:02
As there is no answer since 3 years, I close this issue.

**Closed by fbaligand** 2023-11-11 10:02 UTC
