### ISSUE TITLE
How can we have an option for showing a  link or not

### ISSUE THREAD

**Issue by tracylucky** [fbaligand/kibana-enhanced-table#260] opened 2022-03-07 07:47 UTC
Hi guys,

Thanks for your great plugin.

I'd like to add a column, if the content contains http/https, there will be clickable link. But if the content doesn't have the http/https words, it **should not** be a link, just show the text. could you please give me some help, how  can I make it work, thanks a lot

**Comment by tracylucky** [comment] 2022-03-07 07:55
![Uploading image.png…]()

**Comment by tracylucky** [comment] 2022-03-07 07:56
<img width="703" alt="image" src="https://user-images.githubusercontent.com/7941700/156990489-1b865e8b-1d38-47a5-8332-ea44eddf02f1.png">

**Comment by fbaligand** [comment] 2022-03-07 08:16
Hi,

I tested exactly the formula you give and it works fine for me. I use enhanced-table v1.13.0 with Kibana 7.17.0.

But it should work for a lot of versions, this is not a new feature.
That said, what is your Kibana version and plugin version?

Then, given that you generate html in your formula, you should not use "template" feature, especially since it escapes html chars like `<` and `>`.
By the way, given the screenshot of your settings, you can't get the result on the left: link label should be "aaa" and value could not be displayed as a link, because template escape html special chars.

If you really want to use "template", you can tell to display value without html escaping, using this syntax:
`{{{value}}}`

**Comment by tracylucky** [comment] 2022-03-07 10:49
Thanks for your prompt reply， what my exact formula is **indexOf(col6, "https")> -1?"<a href='" + col6 +"' > " + col6 + "</a>":col6**, if I don't use 'template', how can it work to me? Thanks a lot.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/7941700/157017024-e16e6069-8a78-4c2d-a972-f3ebee016499.png">

**Comment by fbaligand** [comment] 2022-03-07 13:24
OK, with real formula, I understand better now.
So the problem is that "+" does not concatenation (like in javascript). To do concatenation, you have to use `||` operator.
So I invite you to replace all `+` by `||`.

To find documentation on Formula syntax, you can click on "documentation" link above "Formula" field. Then click on "expr-eval" link. You will find there all information about expr-eval syntax (that is the syntax used by Formula).

**Comment by tracylucky** [comment] 2022-03-08 10:48
Thanks, it works. Another question is how can I adjust the column width? now it seems automatically change, but it is not good to view 
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7941700/157223665-cc89e6c0-63cf-413a-b690-9c1f4c78326c.png">

**Comment by fbaligand** [comment] 2022-03-08 11:10
You can use "Cell computed CSS", with something like:
`"width: 10%"`

But I strongly recommend you to use as link label, either a static value either a column reference that is short.

**Comment by tracylucky** [comment] 2022-03-09 04:20
I tried with "width:10%" but it seems it doesn't work for me, 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/7941700/157371800-78822d59-c353-476d-ade3-47feb687dc79.png">， I shorten the link, but same problem

**Comment by fbaligand** [comment] 2022-03-09 08:02
You can eventually try “min-width” and “max-width” CSS attributes

**Comment by tracylucky** [comment] 2022-03-14 02:58
Thanks for your patience, working now, please close this issue, thanks a lot

**Comment by tracylucky** [comment] 2022-03-14 03:50
Hi @fbaligand one more question, how can we have 'filter for the value' for a link, thanks
<img width="242" alt="image" src="https://user-images.githubusercontent.com/7941700/158101802-b252a096-0158-40aa-9835-bdc80ac61bec.png">

**Comment by fbaligand** [comment] 2022-03-14 08:00
Well, the only way to have "Filter for value" that works on a computed column, is to have a Formula with a simple reference to a classic column (ex: `col1`), and then use a template to render the value as a html link (ex: `<a href="https://www.google.com?q={{value}}">link</a>`.

**Comment by tracylucky** [comment] 2022-03-15 08:12
My  formula is a little complicated `_indexOf(col9, "https")> -1?"<a href='" || col9 || "' target='_blank'>click me</a>":col9_, so that is impossible to have the 'Filter for value'?

**Comment by fbaligand** [comment] 2022-03-15 09:43
Yes, in that case, it will no work. Sorry. 
Because in you case, the cell value will be your computed html.

**Comment by fbaligand** [comment] 2022-04-01 11:25
As question is answered, I close the issue.

**Closed by fbaligand** 2022-04-01 11:25 UTC
Labels: question
