### ISSUE TITLE
Enhanced Table for 7.9.x

### ISSUE THREAD

**Issue by ravitandur** [fbaligand/kibana-enhanced-table#136] opened 2020-09-08 13:13 UTC
Elastic released 7.9.0 & 7.9.1 versions, can u please let us know what is enhanced table version which is compatible with  7.9.X.
If you are planning to release 7.9.X compatible version can u please let us know the timelines.

**Comment by fbaligand** [comment] 2020-09-08 15:10
Hi,

This issue is a duplicate of #132

**Closed by fbaligand** 2020-09-08 15:10 UTC
