### ISSUE TITLE
Sort split column after aggregation

### ISSUE THREAD

**Issue by Mudboyzh** [fbaligand/kibana-enhanced-table#216] opened 2021-07-07 03:32 UTC
I found sort split column doesn't work  if I set split row first.

Here is test data:
POST _bulk
{ "index" : { "_index" : "test-index" } }
{ "group" : "a-group", "status": "1-statusA", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "a-group", "status": "2-statusB", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "a-group", "status": "4-statusD", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "a-group", "status": "5-statusE", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "b-group", "status": "1-statusA", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "b-group", "status": "2-statusB", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }
{ "index" : { "_index" : "test-index" } }
{ "group" : "b-group", "status": "3-statusC", "@timestamp" : "2021-07-07T11:05:27.528+08:00" }

ES version: 7.11

I set 
1. Split row with group.
2. Split column with status.
3. Split column sort by alphabetical. (asc)
![image](https://user-images.githubusercontent.com/9887309/124694952-d1f89000-df14-11eb-8112-a91fa6e69d6e.png)

Split columns should be 1-statusA、2-statusB、3-statusC、4-statusD、5-statusE.
Because of a-group missing the status '3-statusC', split column seems just append the column bucket in array.
Is there any way to sort split columns after aggregation?

**Comment by fbaligand** [comment] 2021-07-07 05:46
Hi,

at this time, split columns sorting is not implemented. There is another issue asking the same thing (for date histogram aggregation), so this feature is on the roadmap.

that said, there is a workaround : use « Filters » aggregation for split columns bucket. That way, split columns are fixed and in the order you declare them.

**Comment by fbaligand** [comment] 2021-07-07 05:49
Duplicate of #150

**Comment by fbaligand** [comment] 2022-01-28 22:06
I close this issue, as it is a duplicate of #150

**Closed by fbaligand** 2022-01-28 22:06 UTC
Labels: duplicate
