### ISSUE TITLE
Support for Kibana 8.7.0

### ISSUE THREAD

**Issue by sebprunierserli** [fbaligand/kibana-enhanced-table#319] opened 2023-04-25 14:29 UTC
Could you please release the plugin version for kibana 8.7.0.

Many thanks in advance !

**Comment by fbaligand** [comment] 2023-04-26 20:45
Well, Kibana 8.7 brings breaking changes that requires changes  in enhanced table plugin to be compatible. 
The good news is that I managed to do required changes in enhanced table so that it works with « kibana dev mode ». 
But the bad news is that it doesn’t work with « kibana prod mode ». 
I already tried several ways, but for now, I’m blocked. 
I will comment here when it will be available.

**Comment by mvenukadasula** [comment] 2023-06-18 16:56
@fbaligand really appreciate for managing this plugin.  Is there a tentative plan to release support for 8.7.x and 8.8.x?

**Comment by fbaligand** [comment] 2023-06-19 07:52
Yes, there is a tentative plan.
As explained in my previous comment, it works in kibana dev mode, but not in prod mode (the way you use it through kibana release).
I already spent a lot of time to understand and fix the problem. But for now, it still does not work. I continue to look for the problem.

**Comment by phihdn** [comment] 2023-06-19 08:10
Hi, can I try to build and deploy on the latest commit on the master branch?

**Comment by fbaligand** [comment] 2023-06-19 22:25
Hi @phihdn,

Currently, I haven't commited the version for Kibana 8.7, as it does not work in prod mode.
But here is the current version that you can install on Kibana 8.7.0 (an on Kibana 8.7.1 if you change "kibanaVersion" in kibana.json inside zip file) :
[enhancedTable-8.7.0.zip](https://github.com/fbaligand/kibana-enhanced-table/files/11793530/enhancedTable-8.7.0.zip)

And here is the actual source code:
[enhancedTable-source-8.7.0.zip](https://github.com/fbaligand/kibana-enhanced-table/files/11793542/enhancedTable-source-8.7.0.zip)

Feel free to test it! And if you find a way to fix this version in prod mode, I would be the happiest man in the world! ;)

**Comment by phihdn** [comment] 2023-06-20 14:41
Hi @fbaligand,

Thank you for sharing the zip files. I tried on my Kibana 8.8.0. I changed the version as you guided.
It said the installation was successful but it was not.
```
~$ bin/kibana-plugin install file:///etc/enhancedTable-8.8.0.zip
Attempting to transfer from file:///etc/enhancedTable-8.8.0.zip
Transferring 1036448 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
```
When I tried to list plugins, it's errored:
```
~$ bin/kibana-plugin list

/usr/share/kibana/src/cli_plugin/list/list.js:23
  plugins.forEach(([name]) => {
          ^
Error: Unable to read kibana.json file for plugin enhancedTable
    at /usr/share/kibana/src/cli_plugin/list/list.js:29:13
    at Array.forEach (<anonymous>)
    at list (/usr/share/kibana/src/cli_plugin/list/list.js:23:11)
    at Command.processCommand (/usr/share/kibana/src/cli_plugin/list/index.js:22:18)
    at Command.<anonymous> (/usr/share/kibana/src/cli/command.js:84:20)
    at Command.listener (/usr/share/kibana/node_modules/commander/index.js:370:29)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/usr/share/kibana/node_modules/commander/index.js:892:12)
    at Command.parse (/usr/share/kibana/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/usr/share/kibana/src/cli_plugin/cli.js:41:9)
```

Do you have same behaviors?

**Comment by fbaligand** [comment] 2023-06-20 21:29
Well, first, the aim is to test with Kibana 8.7 (not 8.8 that will be next target).
Then, I don't reproduce your issue, not on Kibana 8.7 nor on Kibana 8.8.
Could you list files inside $KIBANA_HOME/plugins/enhancedTable ?
You should verify that kibana.json is here.
Then could you execute `cat kibana.json` and show here the result?

**Comment by phihdn** [comment] 2023-06-21 03:26
Please ignore my previous comment. I did use kibana user to install the plugin instead root. That caused permission issue. After chmod enhancedTable dir and files, the plugin has been loaded and now I see the error on Kibana when I tried to create new enhancedtable.
Regarding the version, since I have 8.8 ready so I just want to do a quick test while I am setting up the Kibana plugin development environment. I will setup another 8.7 instance to test. I will update here if I found something. Thank you.

**Comment by Hrithik-Manchanda** [comment] 2023-06-23 10:35
Hi @fbaligand,

I would like to experiment this plugin in 8.7 version. It would help me if you push changes to git. I may try something here.

**Comment by fbaligand** [comment] 2023-06-25 22:49
Hi @Hrithik-Manchanda,

To help you, I just published the current version for Kibana 8.7 in "8.7" branch.
So you can checkout 8.7 branch and work on it.
If you manage to find a change that makes it work in "prod" mode, I would enjoy that you create a PR!

**Comment by pchakour** [comment] 2023-07-03 14:48
Hi @fbaligand,

I read in the given source code but I didn't find any mistake. So, I have supposed an issue in the kibana plugin helper and I found this thread: https://github.com/elastic/kibana/issues/154325

A fix seems to be merged in the branch 8.7, unfortunately I tried to build a version with the updated branch but got the same problem :-(
I think you have to notify the Kibana team to resolve this issue.

**Comment by fbaligand** [comment] 2023-07-05 18:02
Hi @pchakour,

First of all, I want to thank you for the time you spent to analyze the problem and look at a potential solution. I really appreciate!

Then, I looked at the issue, and found in the comments 3 potential ways to fix the issue:
- update 8.7 branch to last commit (maybe I would be more lucky than you)
- use 8.8 branch to build a 8.7 version
- in Kibana webpack configuration, set "mode" to "production"

I will try these ways and give feedback here. If it doesn't work, as you mention, I will create an issue on Kibana repository.

**Comment by fbaligand** [comment] 2023-07-06 15:22
Good news: using latest state of Kibana "8.7" branch, I finally manage to build a package that works on Kibana 8.7 standalone (production mode) !

So I should be able to publish soon the packages for Kibana 8.7.x !

Thanks again @pchakour for you help!

**Comment by pchakour** [comment] 2023-07-06 16:08
Great news !!

I must have missed something when I tried to build on my side :thinking: 

Anyway, I'm glad you made it :smile:

**Comment by fbaligand** [comment] 2023-07-06 19:07
Well, I had to modify few things so that it compiles without error. I precise that with kibana v8.7.0 tag, I don’t needed that. 
I had to add a “common” directory (despite I don’t have server code), and I had to remove “IPrivate” export in angular/utils.

**Comment by fbaligand** [comment] 2023-07-07 12:07
I'm glad to announce that Enhanced Table plugin for Kibana 8.7 is out!

You can get package here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.4

**Comment by fbaligand** [comment] 2023-07-09 15:35
New good news, plugin works also with Kibana 8.8!
You can find the packages at the same place:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.4

**Comment by mvenukadasula** [comment] 2023-07-13 05:00
Amazing!!! Thank you @fbaligand

**Comment by F0RMaTC** [comment] 2023-07-25 14:29
and what about 8.9? wink wink

**Comment by fbaligand** [comment] 2023-07-25 18:31
Well, don’t be so hurry, kibana 8.9 is not yet out :)
https://github.com/elastic/kibana/releases

**Comment by fbaligand** [comment] 2023-07-27 21:25
@F0RMaTC 
I'm glad to announce you that Enhanced Table for Kibana 8.9 is out!
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.4/enhanced-table-1.13.4_8.9.0.zip

**Comment by fbaligand** [comment] 2023-09-22 06:54
Enhanced Table for Kibana 8.10 is out!
https://github.com/fbaligand/kibana-enhanced-table/releases/v1.13.5/

**Closed by fbaligand** 2023-09-22 06:54 UTC
Labels: enhancement
