### ISSUE TITLE
ELK v8.9 lost support for Computed column Template referring to other columns

### ISSUE THREAD

**Issue by markwheal** [fbaligand/kibana-enhanced-table#331] opened 2023-09-06 14:48 UTC
In Enhanced Table, I used to be able to include a hover over text for a Computed column, and have it output the value from another column, in this example, another column named "blah".

This template previously would have produced a hover over text, "blah = 123", if the "blah" column had a value, 123.

`<div title="blah = {{col['blah']}} ">{{value}}</div>`

**Comment by fbaligand** [comment] 2023-09-08 19:45
Well, as it is a pure HTML behavior, I don’t know what to answer. It is not tied to the plugin itself, but how your browser interprets your html code.

**Comment by fbaligand** [comment] 2023-09-22 07:02
@markwheal 
I just tested your exact code in a computed column template, and it works fine.
So the problem seems to be your browser interpretation, or else 'blah' column does not exist.

**Comment by fbaligand** [comment] 2024-02-01 13:20
I close the issue, given that the problem is not reproducible and there is no feedback since 6 months.

**Closed** 2024-02-01 13:20 UTC
Labels: question
