### ISSUE TITLE
Enhanced table does not respect Kibana time range filtering

### ISSUE THREAD

**Issue by ddelliosRJ** [fbaligand/kibana-enhanced-table#171] opened 2021-01-28 14:40 UTC
Greetings, 

Maybe this is somewhat answered in a previous topic, but I am facing the following issue:

When trying to create an enhanced table, with count as metric, values seem static, regardless the time range I choose. Is this a Kibana issue? If yes, is there any suggested workaround?

Thanks in advance,
Dimitris

**Comment by fbaligand** [comment] 2021-01-28 21:41
Hi, 
There has been an issue about that, few months ago, for few Kibana versions. 
But it has been fixed since then. 

Can you tell me what is your Kibana version and enhanced table plugin version?

**Comment by ddelliosRJ** [comment] 2021-01-29 07:24
Thanks for the quick response!
I am using the latest table version (1.11.0) with Kibana 7.9.0. I will
upgrade to latest Kibana and see if the problem is fixed!

Στις Πέμ, 28 Ιαν 2021, 23:41 ο χρήστης Fabien Baligand <
notifications@github.com> έγραψε:

**Comment by fbaligand** [comment] 2021-01-29 07:51
Hi,

I just made some tests with Kibana 7.9.3 and enhanced-table 1.11.0 ; and time range selection is processed as expected.
I made tests both on Visualize app and Dashboard app, with Enhanced Table vis and Document Table vis. 
I don't reproduce your issue.

**Comment by ddelliosRJ** [comment] 2021-01-29 08:20
Hey, I upgraded to latest Kibana and everything works great. Thanks again for your time and effort! Much appreciated

**Comment by fbaligand** [comment] 2021-01-29 08:22
Nice to see that it works with last Kibana version!
so I close the issue.

**Closed by fbaligand** 2021-01-29 08:22 UTC
