### ISSUE TITLE
7.6.2 error 'Kibana did not load properly'

### ISSUE THREAD

**Issue by magnuslarsen** [fbaligand/kibana-enhanced-table#98] opened 2020-04-01 12:33 UTC
It seems like the 7.6.2 plugin crashes Kibana (which I think is excessive).
Removing the 7.6.2 plugin fixes this, and Kibana loads perfectly again.

I've tried to usual with removing the plugin and optimize folder, (re)install the plugin, and then restart Kibana, to no help:
```bash
rm -rf /usr/share/kibana/plugins/*
rm -rf /usr/share/kibana/optimize/*
rm -f /usr/share/kibana/optimize/.babel_register_cache.json

# as user 'kibana'
/usr/share/kibana/bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.8.0/enhanced-table-1.8.0_7.6.2.zip
```

Upon loading Kibana, you see this message (and nothing else):
`Kibana did not load properly. Check the server output for more information.`

In the Kibana log, the only error I see is this:
```json
{
  "type": "response",
  "@timestamp": "2020-04-01T12:08:25Z",
  "tags": [],
  "pid": 23482,
  "method": "get",
  "statusCode": 404,
  "req": {
    "url": "/built_assets/css/plugins/enhanced-table/index.light.css",
    "method": "get",
    "headers": {
      "host": "kibana.domain.net:5601",
      "user-agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0",
      "accept": "text/css,*/*;q=0.1",
      "accept-language": "en-US,en;q=0.5",
      "accept-encoding": "gzip, deflate, br",
      "dnt": "1",
      "connection": "keep-alive",
      "referer": "https://kibana.domain.net:5601/"
    },
    "remoteAddress": "10.2.11.149",
    "userAgent": "10.2.11.149",
    "referer": "https://kibana.domain.net:5601/"
  },
  "res": {
    "statusCode": 404,
    "responseTime": 7,
    "contentLength": 9
  },
  "message": "GET /built_assets/css/plugins/enhanced-table/index.light.css 404 7ms - 9.0B"
}
```
A 404 is also displayed in the browser (in the Developer Tools -> networking), with the same URL.
I just verified with my still 7.6.1 installation, and this call is not present at all.

I can't see anything in the release notes, nor the breaking changes notes, regarding this change..

**Comment by fbaligand** [comment] 2020-04-01 14:24
Hi,

Can you unzip package for kibana 7.6.1 into plugins, then modify package.json to write 7.6.2, then remove optimize folder and start kibana again?

I think the problem is more about how I built package for kibana 7.6.2

**Comment by magnuslarsen** [comment] 2020-04-01 16:36
Doing the following (i can't install with the `kibana-plugin` utility, since it is an incompatible version):
```bash
cd /usr/share/kibana/plugins
wget https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.8.0/enhanced-table-1.8.0_7.6.1.zip

su kibana -s /bin/bash
unzip enhanced-table-1.8.0_7.6.1.zip
mv kibana/enhanced-table .
rm -rf kibana/
vim enhanced-table/package.json # update to 7.6.2
exit

rm -rf optimize/*
systemctl restart kibana
```

Gives me this in the log:
`[Error: EACCES: permission denied, lstat '/usr/share/kibana/plugins/enhanced-table/node_modules/atoa']`

Even though the `kibana` user has read-write to ALL the files and folders :(
```bash
/usr/share/kibana# ls -alt plugins/enhanced-table/node_modules/                                                                                                                                                                                                                                                                           
total 4                                                                                                                                                                                                                                                                                                                                                                   
drwxr-xr-x 4 kibana kibana   76 Apr  1 16:23 ..                                                                                                                                                                                                                                                                                                                           
drw-rw-rw- 9 kibana kibana  114 Mar  5 23:44 .                                                                                                                                                                                                                                                                                                                            
drw-rw-rw- 2 kibana kibana   79 Mar  5 23:43 atoa                                                                                                                                                                                                                                                                                                                         
drw-rw-rw- 4 kibana kibana 4096 Mar  5 23:43 contra                                                                                                                                                                                                                                                                                                                       
drw-rw-rw- 4 kibana kibana  138 Mar  5 23:43 crossvent                                                                                                                                                                                                                                                                                                                    
drw-rw-rw- 3 kibana kibana  105 Mar  5 23:43 custom-event                                                                                                                                                                                                                                                                                                                 
drw-rw-rw- 6 kibana kibana  257 Mar  5 23:43 dragula                                                                                                                                                                                                                                                                                                                      
drw-rw-rw- 3 kibana kibana  113 Mar  5 23:43 expr-eval                                                                                                                                                                                                                                                                                                                    
drw-rw-rw- 2 kibana kibana  104 Mar  5 23:43 ticky
```

**Comment by magnuslarsen** [comment] 2020-04-02 06:29
Alright, so this morning I removed optimize and plugins, as per usual.

I then stopped the service for Kibana, downgraded Kibana to 7.6.1, installed the 7.6.1 version plugin, changed package.json to 7.6.2, upgraded Kibana again to 7.6.2, and started the service for Kibana; this seems to work, as you expected.

**Comment by fbaligand** [comment] 2020-04-02 08:22
Nice!
Once I fix my package build, I will publish the right package for Kibana 7.6.2.

**Comment by fbaligand** [comment] 2020-04-04 10:18
Hi @magnuslarsen,

I fixed kibana plugin package build, and published fixed packages for Kibana 7.6.2 and 6.8.8.
You can try it with standard installation way.

So I close the issue.

**Closed by fbaligand** 2020-04-04 10:18 UTC
Labels: bug

**Comment by magnuslarsen** [comment] 2020-04-05 07:05
Can confirm it works now :)

Thanks Fabien!

**Comment by fbaligand** [comment] 2020-04-05 08:46
Nice!
Thanks for the feedback!
