### ISSUE TITLE
Installed the enhanced-table1.9.1_7.8.0 but its not reflecting on visualization

### ISSUE THREAD

**Issue by akash123321** [fbaligand/kibana-enhanced-table#127] opened 2020-07-30 08:52 UTC

**Comment by akash123321** [comment] 2020-07-30 08:54
on Console its showing  log   [08:36:03.885] [info][status][plugin:enhancedTable@1.9.1] Status changed from uninitialized to green - Ready
  
but not reflecting on visualization

**Comment by fbaligand** [comment] 2020-07-30 10:14
Hi, I don’t understand your issue. Can you explain more?

**Comment by akash123321** [comment] 2020-07-30 10:29
Hi,
I installed enhanced table in Kibana_7.8.0.
[XXXXXXXXXXXXX bin]$ **./kibana-plugin install file:///TESTING/autoid/ELKStack/plugins/enhanced-table-1.9.1_7.8.0.zip**
Attempting to transfer from file:///TESTING/autoid/ELKStack/plugins/enhanced-table-1.9.1_7.8.0.zip
Transferring 97702 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete 

Then i restarted the kibana, Its started without error.

**log   [08:07:08.084] [info][status][plugin:enhancedTable@1.9.1] Status changed from uninitialized to green - Ready**

then when open the visualization **to create new Enhanced Table**
Enhanced Table is not present as visualization.

**Comment by fbaligand** [comment] 2020-07-30 11:45
So, if I understand well, you don’t see “enhanced table” in “create new visualization” screen, right?

If so, I invite you to empty your browser cache and retry. 
That said, there is currently a blocking issue on kibana 7.8. So, until it is fixed, I advice you to use kibana 7.7.1 or to wait for fix (issue #116)

**Comment by martinschi** [comment] 2020-08-15 08:30
I just run into the same "issue" with enhanced-table-1.9.1_7.7.1 and as @fbaligand suggested, it was simply caused by the fact that a piece of Kibana loaded in browser kept the old set of plugins, solution was to reload Kibana webpage to get new set of plugins including enhanced-table.

**Comment by fbaligand** [comment] 2020-10-04 23:35
Question is answered so I close the issue.

**Closed by fbaligand** 2020-10-04 23:35 UTC
Labels: question
