### ISSUE TITLE
enhance table with Kinana 7.8.0

### ISSUE THREAD

**Issue by nitinupasani** [fbaligand/kibana-enhanced-table#222] opened 2021-08-15 15:08 UTC
I need help using enhance table plugin with Kibana 7.8.0

I tried version 1.9.2 but looks like it is for Kibana 7.8.1

Which version shall I use for Kibana 7.8.0? We are not in position to upgrade Kibana version. Pl help !

**Comment by fbaligand** [comment] 2021-08-15 17:31
Hi, 
Kibana 7.8.0 is not supported because there is a blocking issue with Kibana 7.8.0 (#116), that has been fixed in Kibana 7.8.1.
So there is no release of enhanced Table 1.9.x for Kibana 7.8.0

So I invite you to upgrade to Kibana 7.8.1.

**Closed** 2021-08-15 17:31 UTC
Labels: question

**Comment by nitinupasani** [comment] 2021-08-15 17:58
We have Kibana 7.8.0 bundled with IBM product. We are asking IBM as how to upgrade but can you please help us as how shall we upgrade from Kibana 7.8.0 to Kibana 7.8.1? Your help much appreciated.

**Comment by fbaligand** [comment] 2021-08-15 19:22
Well, I don’t know how your kibana bundled with IBM product is installed.
But I can just tell you to download and uncompress kibana 7.8.1 archive:
https://www.elastic.co/fr/downloads/past-releases/kibana-7-8-1

**Comment by nitinupasani** [comment] 2021-09-11 15:34
Hello

We cannot upgrade Kibana to 7.8.1 and has to stay with Kibana 7.8.0.

Is there any possibility making enhanced table plugin working with this version? We will really appreciate your help.

Regards,
-n
-----------
Nitin Upasani
Director
YRS Solutions
***@***.******@***.***>
Office: +1 703.279.6580
Mobile: +1 518.763.2255
***@***.***

**Comment by fbaligand** [comment] 2021-09-11 19:51
Well, to be clear, kibana core 7.8.0 has a bug / regression that is critical for kibana enhanced table.
So, the problem is not in kibana enhanced table, and so, I can’t fix it. 
Fortunately, kibana 7.8.1 fixed the bug and that’s why enhanced table is compatible with kibana 7.8.1 and not 7.8.0.
