### ISSUE TITLE
Feature-request: add option for alternating row/column color

### ISSUE THREAD

**Issue by osckal** [fbaligand/kibana-enhanced-table#70] opened 2019-10-23 08:11 UTC
it would be great to have alternating color option (customizable colors) to improve readability. lots of columns and rows tends to be difficult to see.

**Comment by mordekasg** [comment] 2020-02-11 20:51
Is it duplicate of #58?

**Comment by fbaligand** [comment] 2020-02-11 21:45
@mordekasg 
No. #58 asks a bg color if a scripted condition is met. 
Here, it is static striped rows (and cols)

**Comment by fbaligand** [comment] 2020-03-05 23:17
Hi, great news! Enhanced Table plugin v1.8.0 is out with a new option "Striped rows"!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.8.0

**Closed by fbaligand** 2020-03-05 23:17 UTC
Labels: enhancement
