### ISSUE TITLE
Kibana 7.8.0: buckets/metrics are not loaded on Dashboard app

### ISSUE THREAD

**Issue by hoberhol** [fbaligand/kibana-enhanced-table#116] opened 2020-07-13 11:14 UTC
Since the latest version 1.9.1 I'm getting the following error on a dashboard including an enhanced table visualization after the login:

**In computed column "col['cnt'], column with label 'cnt' does not exists.**

![image](https://user-images.githubusercontent.com/65902724/87297113-2c306200-c508-11ea-872b-e0975c4e0f47.png)

In the visualization editor the table is working correct. I can then open the dashboard and from now on all is working fine. After logout/login the error appears again.

![image](https://user-images.githubusercontent.com/65902724/87297571-f344bd00-c508-11ea-8653-b878fe8b984e.png)

![image](https://user-images.githubusercontent.com/65902724/87297582-f8097100-c508-11ea-8a12-2207a0032a93.png)

I tried the following without any luck:

- recreate my tables
- use col1 instead of col['xxx']
- create new simple table (as in the screenshot) with just one computed value
- clear browser cache / restart browser / different browser chrome and firefox

The error appears on all my enhanced table visualizations I'm using in production for a long time already.
After I open one visualization in the editor and close again (does not even have to be saved) the error is gone also for the other visualizations until you relogin.

Thanks for your support.

**Comment by fbaligand** [comment] 2020-07-13 11:28
can you tell me:
- what is your Kibana version?
- what was the last plugin version you installed, that worked fine (without this issue) ?

**Comment by hoberhol** [comment] 2020-07-13 12:33
- what is your Kibana version?
  1.8.0
- what was the last plugin version you installed, that worked fine (without this issue) ?
  1.9.1_7.7.1 (on Kibana 7.7.1)
- when you speak about login/relogin, I guess you speak about Kibana authentication?
  yes, logout and login again to Kibana. 
  The same error exist after I switch the space in Kibana without logout/login

**Comment by fbaligand** [comment] 2020-07-13 13:55
I guess you reverse your two first answers?

**Comment by fbaligand** [comment] 2020-07-13 13:58
To help me see where/when regression happened, could you tell me if you reproduce the issue with enhanced table v1.9.0?
And ideally, if you reproduce the issue with kibana 7.8.0?

**Comment by onDee** [comment] 2020-07-13 15:54
Hi, @fbaligand, I've encountered the same issue.
The issue only occurs on visualizations and after investigations on inspection page I've found that there are no aggregations in the request.

- what is your Kibana version?
 Kibana 7.8.0, enhanced-table-1.9.1_7.8.0

- what was the last plugin version you installed, that worked fine (without this issue)?
enhanced-table-1.9.0_7.6.2

**Comment by fbaligand** [comment] 2020-07-13 16:00
@onDee, thanks for your feedback. 
Well, it seems that issue exists since kibana 7.7 and is not tied to 1.9.1 version. 
To check that, could you test 1.9.1 version with kibana 7.6.2?

**Comment by onDee** [comment] 2020-07-13 19:42
Yes, it works with version enhanced-table-1.9.1_7.6.2

**Comment by hoberhol** [comment] 2020-07-13 20:52
I did some more tests:

**Working with version:**
- elasticsearch-7.7.1
- kibana-7.7.1
- enhanced-table-1.9.1_7.7.1.zip

**Not working with version:**
- elasticsearch-7.8.0
- kibana-7.8.0
- enhanced-table-1.9.1_7.8.0.zip

You can reproduce this as follows:

1. Install the version above from download page
1. Install sample data (I used flight sample data)
1. Create a vizualization and add a computed column referencing the metric count value and save as eg. test

![image](https://user-images.githubusercontent.com/65902724/87352452-552e1280-c55b-11ea-9c2b-254931f59e24.png)

![image](https://user-images.githubusercontent.com/65902724/87350926-df28ac00-c558-11ea-9608-f64de52c4f79.png)

1. Create a new dashboard and add visualization to it and save as eg. test

1. Create a new space with manage space and give it a name

1. Switch to the new created space

1. Switch back to the default space

1. Open the dashboard you just created

- with version 7.8.0 you will see the error

![image](https://user-images.githubusercontent.com/65902724/87351770-3713e280-c55a-11ea-8d4d-d0d9862b4be2.png)

- with version 7.7.1 no error occurs

![image](https://user-images.githubusercontent.com/65902724/87352045-b43f5780-c55a-11ea-904d-050baddd323b.png)



Hope this helps and thanks a lot for your time and support on this topic*

**Comment by fbaligand** [comment] 2020-07-13 22:41
@hoberhol 
Thanks for your precious additional tests!

So it is now clear that the issue is tied to "add Kibana 7.8.0 support" commit.
I will investigate on it.

**Comment by tonykoval** [comment] 2020-07-15 11:09
@hoberhol Do you have also problem with discovery mode in Kibana 7.8,0? Error in console: `Cannot read property 'call' of undefined`

**Comment by hoberhol** [comment] 2020-07-15 14:18
I don't experience any problem with the discover function in Kibana 7.8.0. So far everything is working fine.
The mentioned problem only exists in conjuction with the enhanced table plugin.

**Comment by tonykoval** [comment] 2020-07-16 13:24
@hoberhol thank you, I found out that was caused by the old version of chrome

**Comment by fbaligand** [comment] 2020-07-17 06:43
Hi,
After investigation, I can say that:
- I confirm (and reproduce) the bug
- globally, the bug happens on Dashboard app, and does not happen on Visualize app.
- the bug only happens on Kibana 7.8.0
- the bug is caused by a Kibana core regression in v7.8.0. The 'toExpression' function defined on enhanced table visualization is removed by Kibana core, and so, the plugin can't initialize correctly and load configured buckets/metrics.
- I opened an issue for that on Kibana repository:
https://github.com/elastic/kibana/issues/71384
- In the meantime, I opened also a PR on Kibana repository to avoid the need of 'toExpression' function:
https://github.com/elastic/kibana/pull/71423
- this PR has been merged and should be available in Kibana v7.8.1 or v7.8.2

So for now, I can only invite you either to wait for Kibana 7.8 fix, or to downgrade to Kibana v7.7.1.

**Comment by tonykoval** [comment] 2020-07-28 13:24
Kibana 7.8.1 is released, but I didn't find this fix (71423) in the [release notes](https://www.elastic.co/guide/en/kibana/7.8/release-notes-7.8.1.html).

**Comment by fbaligand** [comment] 2020-07-28 14:20
Well, it is not on release notes. 
But I can insure you that fix is included in kibana 7.8.1. 
Proof is on this page:
https://github.com/elastic/kibana/commits/v7.8.1

You can see that “ [Visualizations] Pass 'aggs' parameter to custom request handlers” is part of v7.8.1 commits. 
Thus, @fabiopipitone tested this morning and confirmed that enhanced table 1.9.1 works with kibana 7.8.1. 

I will provide a package for kibana 7.8.1 as soon as I can. 
But, in the meantime, you can just change kibana version in plugin’s package.json file, and install it on kibana 7.8.1 as is.

**Comment by guillermoc-infocorp** [comment] 2020-07-28 18:51
Hi Fabien!
I downloaded new versions Elasticsearch+Kibana 7.8.1 from elastic.co (Windows Zip files), changed the package.json to 7.8.1 and installed successfully, but the error persists. Maybe I forgot something, 
should I do something additional? please your confirmation.

https://artifacts.elastic.co/downloads/kibana/kibana-7.8.1-windows-x86_64.zip
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-windows-x86_64.zip

**Comment by fabiopipitone** [comment] 2020-07-28 19:07
Hi there, 

this morning I actually tested it to check whether it would work with different types of aggregation and bucket splits and it did work.

I'll carry out some further tests ASAP (tonight most likely) to test other and more specific enhanced table features.

I'll let you know!

**Comment by fbaligand** [comment] 2020-07-28 21:01
@guillermoc-infocorp
Sorry that you still experience some issue.
As @fabiopipitone, I did some tests this afternoon on dashboard app, and it worked fine.
Buckets and Metrics are loaded correctly.

That's why I just published package for Kibana 7.8.1:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.9.1/enhanced-table-1.9.1_7.8.1.zip

I invite you to test with that package on your installation. And I invite you to empty your browser cache, to avoid browser cache side effect.

**Comment by guillermoc-infocorp** [comment] 2020-07-28 21:42
@fbaligand 
When I try with a new visualization and a new dashboard it automatically hides the aggr column. The test was made with simple "metric count" and a term aggr on a string field. When I change to another space and came back, it only shows one column: the count one. When I edit, I see both column. 

After save&return, I see both ok.

With old visualizations, I still see the same error as in 7.8.0

Please let me know if you could replicate it.
Thanks! 
Guillermo.

**Comment by fbaligand** [comment] 2020-07-28 22:30
I just did some more tests, and you’re right, the bug is still there. 

So the good news is that I identified and fixed the bug. 
I will try to release 1.9.2 tomorrow with only one package for kibana 7.8.1

**Comment by guillermoc-infocorp** [comment] 2020-07-28 22:34
Excellent! thank you!

**Comment by fbaligand** [comment] 2020-07-29 17:33
Hi all,

I'm glad to announce that enhanced-table 1.9.2 is out, with display on Dashboard app fixed!
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.1

Don't hesitate to download it, install it, test it and give feedback here to say it works as you expect! :)

BTW, there is also another minor bugfix that happened on Kibana 7.8.
Globally, I invite you to forget enhanced-table use with Kibana 7.8.0.
I will remove the package for 7.8.0 soon, as this bug is severe.

**Comment by guillermoc-infocorp** [comment] 2020-07-29 18:39
Hi @fbaligand  thanks for your notification!

is this the correct package?: 
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.9.2/enhanced-table-1.9.2_7.8.1.zip

(because in your post you write v1.9.1)

I've downloaded this (my link for 1.9.2) and is still hiding me all the buckets columns.
Also the original error still shows for old visualizations.

ES 7.8.1
Kibana 7.8.1
Enhanced-table-1.9.2
Last Chrome with empty caché

thanks in advance!
Guillermo.

**Comment by fbaligand** [comment] 2020-07-30 06:15
Very sad to hear that. 
And very surprised.
I made several tests with this version and I don’t have the errors you quote.

**Comment by hoberhol** [comment] 2020-07-30 07:26
Hi all

I can confirm that the same issue as described in the beginning of this thread still exists with the follwowing versions:

ES 7.8.1
Kibana 7.8.1
Enhanced-table 1.9.2

Thanks a lot for your support on this one.

Hans

**Comment by fabiopipitone** [comment] 2020-07-30 09:39
Hi there, 

I confirm the issue's still there. During my first tests, being unaware of this opened issue, I didn't test the going forth and back to/from a new space and seeing what happens, hence when I noticed it was working with 7.8.1 in the Dashboard section I thought the bug was fixed. 

Unfortunately I tested it with the 7.8.1 stack and release 1.9.2 and the problem's still there, as you can see from the following

![et_192_error](https://user-images.githubusercontent.com/45557452/88907507-0077e080-d259-11ea-9346-37f27f6749e6.gif)

_Fabio_

**Comment by fbaligand** [comment] 2020-07-30 10:20
Thanks all for your feedback.
I will do more tests with xpack version to reproduce the issue and try to fix it. 
I hope it does not require a new kibana code change.

**Comment by alaindixon** [comment] 2020-07-30 22:41
WORKS !! thank you very much.

**Comment by fabiopipitone** [comment] 2020-07-31 07:27
> WORKS !! thank you very much.

Does it? Have you tried refreshing the browser after loading the dashboard? Or switching to a new space and then back to the one with the faulty dashboard? 

Which version of the stack are you using? OSS or basic xpack featured?

**Comment by fbaligand** [comment] 2020-07-31 10:45
Hi all,

I did what  @guillermoc-infocorp did:
- I downloaded Kibana 7.8.1 (default distribution with X-Pack Basic License from elastic.co/downloads)
- I downloaded enhanced-table v1.9.2 (https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.9.2)
- I create a enhanced-table vis, go dashboard, add vis, go to another space, go back to default space, go to Dashboard, and finally refresh my browser page

All these steps work fine, I don't see any bug.

So I invite you (@guillermoc-infocorp, @fabiopipitone, @hoberhol) to fully reinstall the plugin:
- delete "optimize" and "plugins" folder
- install plugin using CLI tool: `kibana-plugin.(bat|sh) install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.9.2/enhanced-table-1.9.2_7.8.1.zip`
- start Kibana

**Comment by fabiopipitone** [comment] 2020-07-31 11:11
Ok so, I made a new test this morning, reinstalling the plugin and, most importantly, using the private browsing in Chrome. In so doing I had no problem at all. I guess it was a problem of something Chrome kept track of at this point. Beautiful!

**Comment by fbaligand** [comment] 2020-07-31 12:37
Great news!

**Comment by guillermoc-infocorp** [comment] 2020-07-31 14:27
Definitely you are right!! Thank you sooo much! All is Ok! 

Only deleting the Optimize folder.

have a nice weekend!

**Comment by fbaligand** [comment] 2020-07-31 14:54
Nice to hear that @guillermoc-infocorp !

**Comment by fbaligand** [comment] 2020-07-31 16:55
After 3 successful checks (plus mine), I definitely consider the bug as resolved!
And so, I’m glad to officially close this issue!

**Closed by fbaligand** 2020-07-31 16:55 UTC
Labels: bug

**Comment by ky-ma** [comment] 2020-08-27 01:41
Hi there, is it possible to get 1.9.2 of Enhanced Table to work on 7.8.0 Kibana since it is the latest supported OpenDistro release of ES/Kibana.

I compiled the plugin without errors:
yarn build --kibana-version 7.8.0

I installed it to kibana with out issues but when i load the visual in Kibana i get "error in visualization cannot read property 'indexpattern' of undefined"

**Comment by fbaligand** [comment] 2020-08-27 04:28
No it is not possible. 
Enhanced table v1.9.2 uses a patch included in kibana 7.8.1 (and not in kibana 7.8.0). 

But If open distro supports 7.8.0, it should also support 7.8.1. 
You can install kibana 7.8.1, and change kibana version in open distro kibana plugins inside its package.json file.
BTW, you can keep elaticsearch 7.8.0

Fabien
