### ISSUE TITLE
All data is not visible on Document Table

### ISSUE THREAD

**Issue by Sagesh** [fbaligand/kibana-enhanced-table#233] opened 2021-11-29 11:52 UTC
Hi Fabien,

I am not seeing one of the row in the grid. When I looked at the data all are similar. I can see the same in "Discover" tab in Kibana.
Your input on the same will be appreciated.

![image](https://user-images.githubusercontent.com/23548722/143862863-0c96cebc-bc42-4f83-a8bc-31a129687cdb.png)

Thanks,
Sagesh

**Comment by fbaligand** [comment] 2021-12-23 12:27
Well, if you see the same thing in Discover tab, it means that the problem is not tied to Enhanced Table.
The reason is probably that this document has no "message" field.
I invite you in Discover tab to click on ">" at the beginning of the line to see details, then click on JSON tab to see original source of the document.
If you don't see any message field or if you see `"message": null`, then it just means that your document has no "message" data.

**Comment by fbaligand** [comment] 2022-11-11 15:20
Given that question is answered, I close the issue.

**Closed by fbaligand** 2022-11-11 15:20 UTC
Labels: question
