### ISSUE TITLE
format when Split columns on date and "Date Range" doesn't work as expected

### ISSUE THREAD

**Issue by MrKuip** [fbaligand/kibana-enhanced-table#28] opened 2019-03-19 10:53 UTC
I have an enhanced table and a metric with "Split Cols".
The Subaggregation is "Date Range".
I have create 3 ranges (each range is a year):
now-1y/y till now
now-2y/y till now-1y/y
now-3y/y till now -2y/y

In the field "JSON Input" I have "{ "format" : "YYYY" }"
I expect that the header-labels are 2019-2018,  2018-2017, and 2017-2016.
But instead I see a header like : 01/01/2015 01:00:00 to 01/01/2016 01:00:00

Is this the intended behaviour?
Is there a way that I can accomplish my expectations?

(When inspecting the response I see the YYYY format has been honoured!)

**Comment by fbaligand** [comment] 2019-03-19 12:22
Could you export your visualization json (on saved object view) and provide it there so that I can reproduce your issue ?

**Comment by MrKuip** [comment] 2019-03-22 07:20
Here is the exported visualization:
[export (7).json.zip](https://github.com/fbaligand/kibana-enhanced-table/files/2995369/export.7.json.zip)

The strange thing is that the "JSON Input" is nowhere to be found in the exported Json!

**Comment by MrKuip** [comment] 2019-03-22 07:28
Here is the exported visualization:
[export (9).json.zip](https://github.com/fbaligand/kibana-enhanced-table/files/2995388/export.9.json.zip)

Here is part of the response WITHOUT the "JSON input":
>
               "1": {
                  "value": 0
                },
                "key": "2016-01-01T00:00:00.000Z-2017-01-01T00:00:00.000Z",
                "from": 1451606400000,
                "from_as_string": "2016-01-01T00:00:00.000Z",
                "to": 1483228800000,
                "to_as_string": "2017-01-01T00:00:00.000Z",
                "doc_count": 0
              },

And here is the response WITH the "JSON input" "{ "format" : "YYYY" }" :
> 
             {
                "1": {
                  "value": 0
                },
                "key": "2016-2017",
                "from": 1451606400000,
                "from_as_string": "2016",
                "to": 1483228800000,
                "to_as_string": "2017",
                "doc_count": 0
              },

**Comment by fbaligand** [comment] 2019-03-22 07:34
Thank you for all these details. 
I will try to reproduce your issue.
And then fix the bug.

**Comment by fbaligand** [comment] 2019-03-24 17:40
Hi @MrKuip ,

I manage to reproduce your issue.
And unfortunately, I have to say that this issue is not because enhanced-table plugin itself, but because of Kibana core.
If you do the same visualization with a standard Data Table with "Split Rows" bucket (instead of "Split Cols"), you will get the same result.
I did some debugging if I can get the right formatted label from what aggregated table providd by Kibana core, but I didn't find such data.
So I can't fix something in enhanced-table.

That said, I invite to do 2 things : 
- open an issue on Kibana repository, with same example but using a standard Data Table with "Split Rows" bucket. Like you, I would love that "format" option is considered by Kibana!
- waiting that issue is solved by Kibana, you can use this tip : 
in Management > Index patterns, create a new scripted field named "StartYear", with script "doc['StartDate']"
in your enhanced-table visualization, use "StartYear" field for your "Split Cols" bucket.

**Comment by MrKuip** [comment] 2019-03-25 07:13
Thank you for your thorough analysis.

I will file a bugreport on the Kibana project.
It seems so obvious that everybody wants/needs this that I'm suprised that it doesn't work.

**Comment by MrKuip** [comment] 2019-03-25 07:33
I have created an issue:
https://github.com/elastic/kibana/issues/33768

**Comment by fbaligand** [comment] 2019-03-25 07:42
Nice!
I just added a comment and +1 on it. 

By the way, have you tested my tip?

**Comment by MrKuip** [comment] 2019-03-25 11:50
I know your tip will work. And I probably am going to use it. Thanks!

But I do not like it that for each new formatting I have to create a new scripted field.

**Comment by fbaligand** [comment] 2019-03-25 14:25
I fully agree with you!
That's why I call it a tip, not a final solution :)

**Comment by fbaligand** [comment] 2019-03-25 14:26
Given that your issue is answered (concerning enhanced-table plugin), I close the issue.
Feel free to reopen if necessary.

**Closed by fbaligand** 2019-03-25 14:26 UTC
Labels: question
