### ISSUE TITLE
Not working in 7.17.0 with Docker

### ISSUE THREAD

**Issue by jannikbuscha** [fbaligand/kibana-enhanced-table#256] opened 2022-02-28 14:46 UTC
I try to install the plugin with this [docker container](https://github.com/deviantony/docker-elk) but it behaves as if no plugin is installed.

I have already tried Shift+F5, Ctrl+F5, Ctrl+Shift+Del and another browser. However, the view still looks like this:
![image](https://user-images.githubusercontent.com/74017697/156003024-b9dd02d6-3315-495d-95e1-25dd7b3bd746.png)

```dockerfile
ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

RUN kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.17.0.zip
```
```yml
kibana:
    env_file:
      - .env
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    networks:
      - elk
    depends_on:
      - elasticsearch
```

**Comment by fbaligand** [comment] 2022-03-03 02:02
Hi,

I’m very surprised of this issue because I tested v1.13.0 with Kibana 7.17.0 (without Docker) and it works fine. A community user also confirmed me that it works fine.

So it seems to be tied to your Docker setup.

Questions:
- have you followed instructions here?
https://github.com/deviantony/docker-elk#how-to-add-plugins
- have you error or warning logs at build or run time?
- Could you connect to your Docker instance (with /bin/sh) and check that $KIBANA_HOME/plugins contains enhancedTable folder, and inside, there is kibana.json, package.json files and target directory?

**Comment by fbaligand** [comment] 2022-11-11 15:18
Given that there is no feedback since several months, I close the issue.

**Closed by fbaligand** 2022-11-11 15:18 UTC
Labels: question
