### ISSUE TITLE
Dashboard does not display data

### ISSUE THREAD

**Issue by alaindixon** [fbaligand/kibana-enhanced-table#126] opened 2020-07-29 09:34 UTC
Hi,

I don't see the data on dashboard unless I go on the graph save it again then go back on dashboard.
Any idea?

Thanks

a
![bug01](https://user-images.githubusercontent.com/5199552/88783715-6e57d580-d18f-11ea-8887-684281ec41c6.png)
![bug02](https://user-images.githubusercontent.com/5199552/88783727-74e64d00-d18f-11ea-80f6-6569a02d7025.png)

lain

**Comment by fbaligand** [comment] 2020-07-29 11:53
I guess that you use kibana 7.8, right?
If so, you probably have the same issue that this one: https://github.com/fbaligand/kibana-enhanced-table/issues/116

I plan to release a bug fix for that tonight.

**Comment by alaindixon** [comment] 2020-07-29 12:11
Thank you, I will wait for the next release.

**Comment by fbaligand** [comment] 2020-07-29 17:30
Close this issue as it is a duplicate of #116

**Closed by fbaligand** 2020-07-29 17:30 UTC
Labels: duplicate

**Comment by fbaligand** [comment] 2020-07-29 17:36
@alaindixon 
as you can see on issue #116, v1.9.2 is out with this bug fixed.
